### ISSUE TITLE
Add link

### ISSUE THREAD

**Issue by insign** [raushankumar27/customgesture#1]
Add https://extensions.gnome.org/extension/2781/custom-3-finger-gestures/ to the desc and readme of your repo. I had to search for.

**Comment by insign** [comment]
BTW, not working for me. Dell XPS 9370, Pop! 20.04. Preferences ok but not working.,

**Comment by raushankumar27** [comment]
Does 4 finger gesture works on you system? Are you using it on wayland session

**Comment by raushankumar27** [comment]
> Add https://extensions.gnome.org/extension/2781/custom-3-finger-gestures/ to the desc and readme of your repo. I had to search for.

Thanks for the suggestion.
