### ISSUE TITLE
Extension installs but doesn't work

### ISSUE THREAD

**Issue by naveenjohnsonv** [raushankumar27/customgesture#2]
No errors during installation but it just doesn't work.
Gnome Version: 3.38
OS: Pop!OS 20.10

**Comment by raushankumar27** [comment]
did you try it on wayland session? does 4 finger geture to switch workspace works?

**Comment by naveenjohnsonv** [comment]
No, x11. 
Nope, 4 finger gestures also do not work.

**Comment by raushankumar27** [comment]
Gesture will not work on x11,.  It works only on Wayland

**Comment by naveenjohnsonv** [comment]
Ah, sorry I didn't see the base repo link.
